#+TITLE: Color, tempo, and dynamics
#+LaTeX_CLASS_OPTIONS: [letter, twoside, twocolumn]
#+OPTIONS: toc:nil

* Continuing harmony

** Yesterday: John Lennon
   How do we characterize the harmony of this song? What is making the
   harmony?  The song begins with  a guitar softly plucked, while John
   Lennon sings a counter melody. The  bass is walking faster than the
   guitar but it is only playing the notes that make up the chord that
   the guitar is playing. Sustained strings are holding chords, making
   it easier to follow when a chord is changed.

** Day Tripper: The beatles
   This songs starts  with a duet of guitars playing  the same melody.
   A bass joins the song, but it  too is playing the same melody.  One
   more guitar is added to the mix, followed by voices, which together
   make a harmony.

** We can work it out
   This song begins with all instruments playing. What made the harmony
   in this song was accordion, bass, and guitar.

** Paperback writer
   This song begins with four voices staggered and singing the chorus.
   The key to the harmony in this song is the bass playing. It appears
   soft in the background.

** Verbum caro factum est
   There are  at least  four voice types  singing this  song: soprano,
   alto, tenor,  and bass. As  they sing  short snippets of  their own
   parts of the songs, staggered in time, and as they sing each others
   parts, a harmony is created.

** Pachabels Canon in D Major
   The way  that harmony  is created  in this song  is that  each bass
   instrument  plays a  melody,  which is  followed  by another  voice
   playing the  second part of  the melody, followed by  another voice
   playing the third notes, all  playing a chord progression. on their
   notes.

** Little Martha
   This song begins with a single guitar playing a melody. A bass line
   joins the song, repeatedly playing the same note. This pattern of
   bass playing is called a /drone based harmony/. The bass line does
   change, but its pace is so slow that it acts like a drone.

* Color, tempo, and dynamics
  
** Defining color
   Like an  artist who paints on  his canvas with different  colors, a
   composer adds  qualitative features.   We recognize  instruments by
   their articulation and  timbre, i.e., its tone color.  We make keys
   by having scales. We talk about the tonality of a scale by bringing
   in  the related  keys of  a  scale.  Thus,  we can  talk about  the
   C-major scale, and talk about the C-major's tonality. When you play
   a note, it contains other overtones in it.
   
   /qualitative features/: characteristics of the sound
   
   /tone color/: timbre (INST/VOC)
   
   /tonality/: key color, overtones, resonance
   
   /quantitative/: degree of expression

** Igor Stravinsky's Le Sacre du printemps
   The song begins with a strained basson. Stravinsky writes a piece
   that pushes the instruments to their extremes.

** Barcarolle 
   The darker colors of the piano in this piece have a different effect
   than the lighter colors of the piano. Professor Ruppert imagines 
   Venice, where a boatman is rowing the boat is represented by the left
   hand and he sings his love song with his right hand.

** Lieutnant Kije suite
   In this song, we are supposed to feel that we are in Russia, riding
   inside a troika.


* Texture

** Definitions
/texture/: the  interweaving of melody  and harmony; sound  aspects of
musical  structure  vertically,  horizontally,   or  with  respect  to
qualitative/quantitative  features of  tone  color, articulation,  and
dynamic level; the fabric of music

/monophony/: one sound, simply a melody

/homophony/: same sounds, a harmonious melody

/heterophony/:  different   sounds,  people  playing  the   same  song
differently

/polyphony/:

/antiphony/: sounds that are against,  perhaps two choirs that operate
independtly, but there is a dialogue

/ostinato/: an instrument or group  of instruments that do their thing
independent of what the rest of the music is doing

/homorhythm/: when all instruments are playing a single rhythm

** Chant example
   The song begins with several people singing one melody, hence, this
   is considered /monophony/.

** Pennylane
   Since the voice is the most important part of this song, we have a
   basic homophony.

* Definitions
